/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/router'
import { Route as PokemonsRouteImport } from './routes/pokemons'

const PokemonsRoute = PokemonsRouteImport.update({
  id: '/pokemons',
  path: '/pokemons',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/pokemons': typeof PokemonsRoute
}
export interface FileRoutesByTo {
  '/pokemons': typeof PokemonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/pokemons': typeof PokemonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/pokemons'
  fileRoutesByTo: FileRoutesByTo
  to: '/pokemons'
  id: '__root__' | '/pokemons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PokemonsRoute: typeof PokemonsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pokemons': {
      id: '/pokemons'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof PokemonsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PokemonsRoute: PokemonsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
